#!/bin/bash

options=(
	style=round
	width=4.0
	hidpi=true
	active_color=0xffe2e2e3
	inactive_color=0xff414550
	blacklist="System Preferences,System Settings,Finder,ChatGPT,Bitwarden,Steam Helper,steamwebhelper.exe"
)

borders "${options[@]}"
